sequence:
  path: "/media/hydran00/CrucialX9/Nardi/Nardi_R-AL_2026/VolumeDeform/upperbody"
  # path: "/media/hydran00/CrucialX9/Nardi/Nardi_R-AL_2026/VolumeDeform/boxing"
  format: "tum"   # tum | icl | raw
  depth_scale: 0.001
  start_frame: 0
  max_frames: -1

camera:
  fx: 570.342
  fy: 570.342
  cx: 320.0
  cy: 240.0
  width: 640
  height: 480

tsdf:
  dims: [192, 192, 192]
  voxel_size: 0.008
  truncation: 0.04
  origin: [-0.768, -0.768, 0.05]

solver:
  gn_iterations: 30
  pcg_iterations: 24
  lambda_smooth: 10.0
  lambda_damping: 5.0

warp:
  node_radius: 0.10
  node_min_dist: 0.06
  max_nodes: 1024
  node_update_every_n: 10
  max_dx_mean: 0.03
  max_update_rot: 0.02
  max_update_trans: 0.01
  update_scale: 0.10
  integrate_warped: true
  integrate_min_optimized_count: 3
  integrate_unwarped_fallback: false

icp:
  rigid_tracking: true
  dist_threshold: 0.06
  angle_threshold: 0.75
  view_threshold: 0.2
  search_radius_px: 8
  min_valid_corrs: 500

sift:
  enabled: false
  max_features: 8192
  max_history: 8
  max_matches_per_frame: 48
  octaves: 5
  threshold: 3.0
  max_match_error: 5.0
  max_ambiguity: 0.85
  max_3d_dist: 0.08
  weight: 0.25

bbox:
  enabled: true
  min_pt: [-1.0, -1.0, 0.01]
  max_pt: [1.0, 1.0, 1.8]

visualizer:
  enabled: true
