sequence:
  path: "/media/hydran00/CrucialX9/Nardi/Nardi_R-AL_2026/VolumeDeform/Umbrella"
  # path: "/media/hydran00/CrucialX9/Nardi/Nardi_R-AL_2026/VolumeDeform/boxing"
  format: "tum"   # tum | icl | raw
  depth_scale: 0.001
  start_frame: 0
  max_frames: -1

camera:
  fx: 570.342
  fy: 570.342
  cx: 320.0
  cy: 240.0
  width: 640
  height: 480

tsdf:
  dims: [256, 256, 256]
  voxel_size: 0.006
  truncation: 0.03
  origin: [-0.768, -0.768, 0.05]

solver:
  gn_iterations: 2
  pcg_iterations: 40
  lambda_smooth: 150.0
  lambda_damping: 2.0

warp:
  node_radius: 0.08
  node_min_dist: 0.04
  max_nodes: 4096
  node_update_every_n: 0
  max_dx_mean: 0.05
  max_update_rot: 0.01
  max_update_trans: 0.005
  update_scale: 0.15
  integrate_warped: false # todo remove 
  integrate_unwarped_fallback: false

icp:
  dist_threshold: 0.04
  angle_threshold: 0.9
  view_threshold: 0.2
  search_radius_px: 16
  min_valid_corrs: 2000

sift:
  enabled: true
  max_features: 8192
  max_history: 8
  max_matches_per_frame: 48
  octaves: 5
  threshold: 3.0
  max_match_error: 5.0
  max_ambiguity: 0.85
  max_3d_dist: 0.08
  weight: 0.25

bbox:
  enabled: true
  min_pt: [-1.0, -1.0, 0.01]
  max_pt: [1.0, 1.0, 2.0]

visualizer:
  enabled: true
