sequence:
  # path: "/media/hydran00/CrucialX9/Nardi/Nardi_R-AL_2026/VolumeDeform/upperbody"
  path: "/media/hydran00/CrucialX9/Nardi/Nardi_R-AL_2026/VolumeDeform/upperbody"
  format: "tum"   # tum | icl | raw
  depth_scale: 0.001
  start_frame: 0
  max_frames: -1

camera:
  fx: 570.342
  fy: 570.342
  cx: 320.0
  cy: 240.0
  width: 640
  height: 480

tsdf:
  dims: [256, 256, 256]
  voxel_size: 0.005
  truncation: 0.02
  origin: [-0.7, -0.7, 0.0]
  decay_alpha: 0.9
  max_weight: 50.0

solver:
  gn_iterations: 0
  pcg_iterations: 0
  lambda_smooth: 30.0 # arap
  lambda_damping: 1.0
  debug: false
warp:
  node_radius: 0.02
  node_min_dist: 0.015
  max_nodes: 4016
  node_update_every_n: 20000
  prune_nodes: true
  prune_disconnected: true
  prune_min_observed_voxels: 2
  prune_min_surface_voxels: 3
  prune_min_component_size: 4
  prune_support_radius_factor: 0.75
  prune_surface_tsdf_abs: 0.28
  prune_empty_tsdf: 0.55

  max_dx_mean: 0.2
  max_update_rot: 0.2
  max_update_trans: 0.1
  update_scale: 0.0
  integrate_warped: true
  integrate_min_optimized_count: 1
  integrate_unwarped_fallback: false

# icp:
#   dist_threshold: 0.015
#   angle_threshold: 0.75
#   view_threshold: 0.15
#   search_radius_px: 3
#   min_valid_corrs: 5000

icp:
  rigid_tracking: true
  dist_threshold: 0.08
  angle_threshold: 0.5
  view_threshold: 0.2
  search_radius_px: 20

sift:
  enabled: true
  max_features: 8192
  max_history: 12
  max_matches_per_frame: 96
  octaves: 5
  threshold: 2.0
  max_match_error: 5.0
  max_ambiguity: 1.0
  max_3d_dist: 0.1
  weight: 0.4


profiler:
  enabled: true
  every_n: 1
  quiet: false

bbox:
  enabled: false
  min_pt: [-1.0, -1.0, 0.01]
  max_pt: [1.0, 1.0, 1.8]

visualizer:
  enabled: true
